- hosts: localhost
  remote_user: root
  vars:
    debug_params:
      msg: "hello there"
  tasks:

  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600

  - name: Upgrade APT to the latest packages
    apt: upgrade=dist
    register: apt_result

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"

  - name: Purge residual kernel packages
    shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"

  - name: install basic packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - build-essential 
      - libgmp-dev
      - libx11-6 
      - libx11-dev
      - flex
      - libncurses5 
      - libncurses5-dev
      - libncursesw5 
      - libpcsclite-dev
      - zlib1g-dev 
      - libmpc3 
      - lemon 
      - aptitude 
      - libtinfo-dev
      - libtool
      - shtool 
      - autoconf 
      - git-core
      - pkg-config
      - make 
      - libmpfr-dev 
      - libmpfr4
      - libmpc-dev
      - libtalloc-dev
      - libfftw3-dev
      - libgnutls28-dev 
      - libssl1.0-dev 
      - osmo-bts
      - osmocom-nitb
      - libxml2-dev
      - automake
      - linux-headers-4.15.0-kali2-all-amd64
      - alsa-oss
      - zlibc
      - libgmp3-dev
      - flex 
      - bison 
      - libncurses5-dbg
      - libncurses5-dev 
      - libncursesw5-dbg
      - libncursesw5-dev
      - libtool-bin
      - libsofia-sip-ua-dev
      - sofia-sip-bin
      - texinfo 
# Add source repository into sources list.
  - apt_repository:
      repo: deb http://old.kali.org/kali sana main non-free contrib
      state: present
     
  - name: gcc-4.9
    apt:
      name: gcc-4.9
      state: present

  - name: g++-4.9
    apt:
      name: g++-4.9
      state: present
  
  - apt_repository:
      repo: deb http://old.kali.org/kali sana main non-free contrib
      state: absent
  
  - name: gcc-version_4.9
    shell: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 10

  - name: gcc-version_7
    shell: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20

  - name: g++-version_4.9
    shell: update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 10

  - name: g++-version_7
    shell: update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
 
  - name: config_gcc_1
    shell:  update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
    register: apt_result

  - name: config_gcc_2
    shell:  update-alternatives --set cc /usr/bin/gcc

  - name: config_g++_1
    shell: update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30

  - name: config_g++_2
    shell:  update-alternatives --set c++ /usr/bin/g++

  - name: config_gcc
    shell: update-alternatives --set gcc "/usr/bin/gcc-4.9"
  
  - name: config_g++
    shell: update-alternatives --set g++ "/usr/bin/g++-4.9"

  - name: gnuarm
    shell: rm -rf /root/gnuarm && cd /root && git clone https://github.com/axilirator/gnu-arm-installer.git gnuarm

  - name: download cross-compiler sources
    shell: cd /root/gnuarm && ./download.sh

  - name: build cross compiler
    shell: cd /root/gnuarm && ./build.sh

  - name: libosmocore
    shell: rm -rf /root/libosmocore && cd /root && git clone git://git.osmocom.org/libosmocore.git && cd /root/libosmocore && autoreconf -i && ./configure && make && make install && ldconfig

  - name: libosmo-dsp
    shell: rm -rf /root/libosmo-dsp && cd /root && git clone git://git.osmocom.org/libosmo-dsp.git && cd libosmo-dsp && autoreconf -i && ./configure && make && make install && ldconfig

  - name: osmocombb-trx
    shell: rm -rf /root/osmocom-ansible && git clone https://github.com/bbaranoff/osmocom-ansible && rm -rf /root/trx && cd /root && export PATH=$PATH:/root/gnuarm/install/bin && git clone git://git.osmocom.org/osmocom-bb.git trx && cd trx && git checkout jolly/testing && cp /root/osmocom-ansible/Makefile /root/trx/src/target/firmware/Makefile && cd src && make HOST_layer23_CONFARGS=--enable-transceiver

  - name: asterisk
    shell: rm -rf /root/asterisk-1.8.13.1* /root/imsi-catcher && cd /root && git clone https://github.com/bastienbaranoff/imsi-catcher && wget https://downloads.asterisk.org/pub/telephony/asterisk/old-releases/asterisk-1.8.13.1.tar.gz && gzip -dc <  asterisk-1.8.13.1.tar.gz | tar -xf - && cp /root/imsi-catcher/tcptls.c /root/asterisk-1.8.13.1/main/tcptls.c

  - name: asterisk-install
    shell: cd /root/asterisk-1.8.13.1 && ./configure && make && make install
  
  - name: asterisk-config
    shell: cp -r ~/imsi-catcher/asterisk/ /etc/

  - apt_repository:
      repo: deb http://old.kali.org/kali moto main non-free contrib
      state: present

  - apt_repository:
      repo: deb http://http.kali.org/kali kali-rolling main non-free contrib
      state: absent

  - name: asterisk-dev
    apt:
      name: asterisk-dev
      state: present

  - apt_repository:
      repo: deb http://old.kali.org/kali moto main non-free contrib
      state: absent

  - apt_repository:
      repo: deb http://http.kali.org/kali kali-rolling main non-free contrib
      state: present

  - name: opencore-amr
    shell: rm -rf /root/opencore-amr && cd /root && git clone https://github.com/VFR-maniac/opencore-amr && cd opencore-amr && autoreconf -i && ./configure && make && make install && ldconfig
 
  - name: mISDN
    shell: rm -rf /root/mISDN /root/mISDNuser && rm -Rf /lib/modules/$(uname -r)/kernel/drivers/isdn/hardware/mISDN && rm -Rf /lib/modules/$(uname -r)/kernel/drivers/isdn/mISDN/  && depmod -a && cd /root/ && git clone https://github.com/b1-systems/mISDN/ && git clone https://github.com/b1-systems/mISDNuser/ && cd mISDN && cp /root/osmocom-ansible/mISDN.patch mISDN.patch && patch -p1 < mISDN.patch &&  aclocal && automake --add-missing && ./configure && cp /root/osmocom-ansible/mISDN.cfg.default standalone/mISDN.cfg && make modules && make modules_install && depmod -a && cd ../mISDNuser && make && ./configure && make && make install && cd example && make 

  - name: lcr
    shell: rm -rf /root/lcr && cd /root && git clone https://github.com/fairwaves/lcr && cd lcr &&  autoreconf -fi && ./configure --with-sip --with-gsm-bs --with-gsm-ms --enable-gsmhr --with-asterisk && make && make install && ldconfig

  - name: ending
    shell: rm -rf /root/.osmocom && cp /root/lcr/chan_lcr.so /usr/lib/asterisk/modules/ && cp /root/imsi-catcher/directory.list /usr/local/etc/lcr/ && cp /root/imsi-catcher/interface.conf /usr/local/etc/lcr/ && cp /root/imsi-catcher/options.conf /usr/local/etc/lcr/ && cp /root/imsi-catcher/routing.conf /usr/local/etc/lcr/ && mkdir /root/.osmocom && cp /root/imsi-catcher/open-bsc.cfg /root/.osmocom/ && cp /root/imsi-catcher/osmo-bts.cfg /root/.osmocom/ && cp /root/imsi-catcher/asterisk 

